parameter_sets:
- qtl_n: 16
  rep: 1
  sample_size: 1000
  scaling: 0.1
- qtl_n: 16
  rep: 2
  sample_size: 1000
  scaling: 0.1
- qtl_n: 16
  rep: 3
  sample_size: 1000
  scaling: 0.1
- qtl_n: 16
  rep: 4
  sample_size: 1000
  scaling: 0.1
- qtl_n: 16
  rep: 5
  sample_size: 1000
  scaling: 0.1
- qtl_n: 16
  rep: 6
  sample_size: 1000
  scaling: 0.1
- qtl_n: 16
  rep: 7
  sample_size: 1000
  scaling: 0.1
- qtl_n: 16
  rep: 8
  sample_size: 1000
  scaling: 0.1
- qtl_n: 16
  rep: 9
  sample_size: 1000
  scaling: 0.1
- qtl_n: 16
  rep: 10
  sample_size: 1000
  scaling: 0.1
- qtl_n: 22
  rep: 1
  sample_size: 1000
  scaling: 0.2
- qtl_n: 22
  rep: 2
  sample_size: 1000
  scaling: 0.2
- qtl_n: 22
  rep: 3
  sample_size: 1000
  scaling: 0.2
- qtl_n: 22
  rep: 4
  sample_size: 1000
  scaling: 0.2
- qtl_n: 22
  rep: 5
  sample_size: 1000
  scaling: 0.2
- qtl_n: 22
  rep: 6
  sample_size: 1000
  scaling: 0.2
- qtl_n: 22
  rep: 7
  sample_size: 1000
  scaling: 0.2
- qtl_n: 22
  rep: 8
  sample_size: 1000
  scaling: 0.2
- qtl_n: 22
  rep: 9
  sample_size: 1000
  scaling: 0.2
- qtl_n: 22
  rep: 10
  sample_size: 1000
  scaling: 0.2
- qtl_n: 26
  rep: 1
  sample_size: 1000
  scaling: 0.3
- qtl_n: 26
  rep: 2
  sample_size: 1000
  scaling: 0.3
- qtl_n: 26
  rep: 3
  sample_size: 1000
  scaling: 0.3
- qtl_n: 26
  rep: 4
  sample_size: 1000
  scaling: 0.3
- qtl_n: 26
  rep: 5
  sample_size: 1000
  scaling: 0.3
- qtl_n: 26
  rep: 6
  sample_size: 1000
  scaling: 0.3
- qtl_n: 26
  rep: 7
  sample_size: 1000
  scaling: 0.3
- qtl_n: 26
  rep: 8
  sample_size: 1000
  scaling: 0.3
- qtl_n: 26
  rep: 9
  sample_size: 1000
  scaling: 0.3
- qtl_n: 26
  rep: 10
  sample_size: 1000
  scaling: 0.3
- qtl_n: 32
  rep: 1
  sample_size: 1000
  scaling: 0.5
- qtl_n: 32
  rep: 2
  sample_size: 1000
  scaling: 0.5
- qtl_n: 32
  rep: 3
  sample_size: 1000
  scaling: 0.5
- qtl_n: 32
  rep: 4
  sample_size: 1000
  scaling: 0.5
- qtl_n: 32
  rep: 5
  sample_size: 1000
  scaling: 0.5
- qtl_n: 32
  rep: 6
  sample_size: 1000
  scaling: 0.5
- qtl_n: 32
  rep: 7
  sample_size: 1000
  scaling: 0.5
- qtl_n: 32
  rep: 8
  sample_size: 1000
  scaling: 0.5
- qtl_n: 32
  rep: 9
  sample_size: 1000
  scaling: 0.5
- qtl_n: 32
  rep: 10
  sample_size: 1000
  scaling: 0.5
- qtl_n: 46
  rep: 1
  sample_size: 1000
  scaling: 1.0
- qtl_n: 46
  rep: 2
  sample_size: 1000
  scaling: 1.0
- qtl_n: 46
  rep: 3
  sample_size: 1000
  scaling: 1.0
- qtl_n: 46
  rep: 4
  sample_size: 1000
  scaling: 1.0
- qtl_n: 46
  rep: 5
  sample_size: 1000
  scaling: 1.0
- qtl_n: 46
  rep: 6
  sample_size: 1000
  scaling: 1.0
- qtl_n: 46
  rep: 7
  sample_size: 1000
  scaling: 1.0
- qtl_n: 46
  rep: 8
  sample_size: 1000
  scaling: 1.0
- qtl_n: 46
  rep: 9
  sample_size: 1000
  scaling: 1.0
- qtl_n: 46
  rep: 10
  sample_size: 1000
  scaling: 1.0
- qtl_n: 64
  rep: 1
  sample_size: 1000
  scaling: 2.0
- qtl_n: 64
  rep: 2
  sample_size: 1000
  scaling: 2.0
- qtl_n: 64
  rep: 3
  sample_size: 1000
  scaling: 2.0
- qtl_n: 64
  rep: 4
  sample_size: 1000
  scaling: 2.0
- qtl_n: 64
  rep: 5
  sample_size: 1000
  scaling: 2.0
- qtl_n: 64
  rep: 6
  sample_size: 1000
  scaling: 2.0
- qtl_n: 64
  rep: 7
  sample_size: 1000
  scaling: 2.0
- qtl_n: 64
  rep: 8
  sample_size: 1000
  scaling: 2.0
- qtl_n: 64
  rep: 9
  sample_size: 1000
  scaling: 2.0
- qtl_n: 64
  rep: 10
  sample_size: 1000
  scaling: 2.0
- qtl_n: 90
  rep: 1
  sample_size: 1000
  scaling: 4.0
- qtl_n: 90
  rep: 2
  sample_size: 1000
  scaling: 4.0
- qtl_n: 90
  rep: 3
  sample_size: 1000
  scaling: 4.0
- qtl_n: 90
  rep: 4
  sample_size: 1000
  scaling: 4.0
- qtl_n: 90
  rep: 5
  sample_size: 1000
  scaling: 4.0
- qtl_n: 90
  rep: 6
  sample_size: 1000
  scaling: 4.0
- qtl_n: 90
  rep: 7
  sample_size: 1000
  scaling: 4.0
- qtl_n: 90
  rep: 8
  sample_size: 1000
  scaling: 4.0
- qtl_n: 90
  rep: 9
  sample_size: 1000
  scaling: 4.0
- qtl_n: 90
  rep: 10
  sample_size: 1000
  scaling: 4.0
- qtl_n: 120
  rep: 1
  sample_size: 1000
  scaling: 7.0
- qtl_n: 120
  rep: 2
  sample_size: 1000
  scaling: 7.0
- qtl_n: 120
  rep: 3
  sample_size: 1000
  scaling: 7.0
- qtl_n: 120
  rep: 4
  sample_size: 1000
  scaling: 7.0
- qtl_n: 120
  rep: 5
  sample_size: 1000
  scaling: 7.0
- qtl_n: 120
  rep: 6
  sample_size: 1000
  scaling: 7.0
- qtl_n: 120
  rep: 7
  sample_size: 1000
  scaling: 7.0
- qtl_n: 120
  rep: 8
  sample_size: 1000
  scaling: 7.0
- qtl_n: 120
  rep: 9
  sample_size: 1000
  scaling: 7.0
- qtl_n: 120
  rep: 10
  sample_size: 1000
  scaling: 7.0
- qtl_n: 156
  rep: 1
  sample_size: 1000
  scaling: 12.0
- qtl_n: 156
  rep: 2
  sample_size: 1000
  scaling: 12.0
- qtl_n: 156
  rep: 3
  sample_size: 1000
  scaling: 12.0
- qtl_n: 156
  rep: 4
  sample_size: 1000
  scaling: 12.0
- qtl_n: 156
  rep: 5
  sample_size: 1000
  scaling: 12.0
- qtl_n: 156
  rep: 6
  sample_size: 1000
  scaling: 12.0
- qtl_n: 156
  rep: 7
  sample_size: 1000
  scaling: 12.0
- qtl_n: 156
  rep: 8
  sample_size: 1000
  scaling: 12.0
- qtl_n: 156
  rep: 9
  sample_size: 1000
  scaling: 12.0
- qtl_n: 156
  rep: 10
  sample_size: 1000
  scaling: 12.0
- qtl_n: 202
  rep: 1
  sample_size: 1000
  scaling: 20.0
- qtl_n: 202
  rep: 2
  sample_size: 1000
  scaling: 20.0
- qtl_n: 202
  rep: 3
  sample_size: 1000
  scaling: 20.0
- qtl_n: 202
  rep: 4
  sample_size: 1000
  scaling: 20.0
- qtl_n: 202
  rep: 5
  sample_size: 1000
  scaling: 20.0
- qtl_n: 202
  rep: 6
  sample_size: 1000
  scaling: 20.0
- qtl_n: 202
  rep: 7
  sample_size: 1000
  scaling: 20.0
- qtl_n: 202
  rep: 8
  sample_size: 1000
  scaling: 20.0
- qtl_n: 202
  rep: 9
  sample_size: 1000
  scaling: 20.0
- qtl_n: 202
  rep: 10
  sample_size: 1000
  scaling: 20.0
- qtl_n: 46
  rep: 1
  sample_size: 10000
  scaling: 0.1
- qtl_n: 46
  rep: 2
  sample_size: 10000
  scaling: 0.1
- qtl_n: 46
  rep: 3
  sample_size: 10000
  scaling: 0.1
- qtl_n: 46
  rep: 4
  sample_size: 10000
  scaling: 0.1
- qtl_n: 46
  rep: 5
  sample_size: 10000
  scaling: 0.1
- qtl_n: 46
  rep: 6
  sample_size: 10000
  scaling: 0.1
- qtl_n: 46
  rep: 7
  sample_size: 10000
  scaling: 0.1
- qtl_n: 46
  rep: 8
  sample_size: 10000
  scaling: 0.1
- qtl_n: 46
  rep: 9
  sample_size: 10000
  scaling: 0.1
- qtl_n: 46
  rep: 10
  sample_size: 10000
  scaling: 0.1
- qtl_n: 64
  rep: 1
  sample_size: 10000
  scaling: 0.2
- qtl_n: 64
  rep: 2
  sample_size: 10000
  scaling: 0.2
- qtl_n: 64
  rep: 3
  sample_size: 10000
  scaling: 0.2
- qtl_n: 64
  rep: 4
  sample_size: 10000
  scaling: 0.2
- qtl_n: 64
  rep: 5
  sample_size: 10000
  scaling: 0.2
- qtl_n: 64
  rep: 6
  sample_size: 10000
  scaling: 0.2
- qtl_n: 64
  rep: 7
  sample_size: 10000
  scaling: 0.2
- qtl_n: 64
  rep: 8
  sample_size: 10000
  scaling: 0.2
- qtl_n: 64
  rep: 9
  sample_size: 10000
  scaling: 0.2
- qtl_n: 64
  rep: 10
  sample_size: 10000
  scaling: 0.2
- qtl_n: 78
  rep: 1
  sample_size: 10000
  scaling: 0.3
- qtl_n: 78
  rep: 2
  sample_size: 10000
  scaling: 0.3
- qtl_n: 78
  rep: 3
  sample_size: 10000
  scaling: 0.3
- qtl_n: 78
  rep: 4
  sample_size: 10000
  scaling: 0.3
- qtl_n: 78
  rep: 5
  sample_size: 10000
  scaling: 0.3
- qtl_n: 78
  rep: 6
  sample_size: 10000
  scaling: 0.3
- qtl_n: 78
  rep: 7
  sample_size: 10000
  scaling: 0.3
- qtl_n: 78
  rep: 8
  sample_size: 10000
  scaling: 0.3
- qtl_n: 78
  rep: 9
  sample_size: 10000
  scaling: 0.3
- qtl_n: 78
  rep: 10
  sample_size: 10000
  scaling: 0.3
- qtl_n: 102
  rep: 1
  sample_size: 10000
  scaling: 0.5
- qtl_n: 102
  rep: 2
  sample_size: 10000
  scaling: 0.5
- qtl_n: 102
  rep: 3
  sample_size: 10000
  scaling: 0.5
- qtl_n: 102
  rep: 4
  sample_size: 10000
  scaling: 0.5
- qtl_n: 102
  rep: 5
  sample_size: 10000
  scaling: 0.5
- qtl_n: 102
  rep: 6
  sample_size: 10000
  scaling: 0.5
- qtl_n: 102
  rep: 7
  sample_size: 10000
  scaling: 0.5
- qtl_n: 102
  rep: 8
  sample_size: 10000
  scaling: 0.5
- qtl_n: 102
  rep: 9
  sample_size: 10000
  scaling: 0.5
- qtl_n: 102
  rep: 10
  sample_size: 10000
  scaling: 0.5
- qtl_n: 142
  rep: 1
  sample_size: 10000
  scaling: 1.0
- qtl_n: 142
  rep: 2
  sample_size: 10000
  scaling: 1.0
- qtl_n: 142
  rep: 3
  sample_size: 10000
  scaling: 1.0
- qtl_n: 142
  rep: 4
  sample_size: 10000
  scaling: 1.0
- qtl_n: 142
  rep: 5
  sample_size: 10000
  scaling: 1.0
- qtl_n: 142
  rep: 6
  sample_size: 10000
  scaling: 1.0
- qtl_n: 142
  rep: 7
  sample_size: 10000
  scaling: 1.0
- qtl_n: 142
  rep: 8
  sample_size: 10000
  scaling: 1.0
- qtl_n: 142
  rep: 9
  sample_size: 10000
  scaling: 1.0
- qtl_n: 142
  rep: 10
  sample_size: 10000
  scaling: 1.0
- qtl_n: 202
  rep: 1
  sample_size: 10000
  scaling: 2.0
- qtl_n: 202
  rep: 2
  sample_size: 10000
  scaling: 2.0
- qtl_n: 202
  rep: 3
  sample_size: 10000
  scaling: 2.0
- qtl_n: 202
  rep: 4
  sample_size: 10000
  scaling: 2.0
- qtl_n: 202
  rep: 5
  sample_size: 10000
  scaling: 2.0
- qtl_n: 202
  rep: 6
  sample_size: 10000
  scaling: 2.0
- qtl_n: 202
  rep: 7
  sample_size: 10000
  scaling: 2.0
- qtl_n: 202
  rep: 8
  sample_size: 10000
  scaling: 2.0
- qtl_n: 202
  rep: 9
  sample_size: 10000
  scaling: 2.0
- qtl_n: 202
  rep: 10
  sample_size: 10000
  scaling: 2.0
- qtl_n: 284
  rep: 1
  sample_size: 10000
  scaling: 4.0
- qtl_n: 284
  rep: 2
  sample_size: 10000
  scaling: 4.0
- qtl_n: 284
  rep: 3
  sample_size: 10000
  scaling: 4.0
- qtl_n: 284
  rep: 4
  sample_size: 10000
  scaling: 4.0
- qtl_n: 284
  rep: 5
  sample_size: 10000
  scaling: 4.0
- qtl_n: 284
  rep: 6
  sample_size: 10000
  scaling: 4.0
- qtl_n: 284
  rep: 7
  sample_size: 10000
  scaling: 4.0
- qtl_n: 284
  rep: 8
  sample_size: 10000
  scaling: 4.0
- qtl_n: 284
  rep: 9
  sample_size: 10000
  scaling: 4.0
- qtl_n: 284
  rep: 10
  sample_size: 10000
  scaling: 4.0
- qtl_n: 376
  rep: 1
  sample_size: 10000
  scaling: 7.0
- qtl_n: 376
  rep: 2
  sample_size: 10000
  scaling: 7.0
- qtl_n: 376
  rep: 3
  sample_size: 10000
  scaling: 7.0
- qtl_n: 376
  rep: 4
  sample_size: 10000
  scaling: 7.0
- qtl_n: 376
  rep: 5
  sample_size: 10000
  scaling: 7.0
- qtl_n: 376
  rep: 6
  sample_size: 10000
  scaling: 7.0
- qtl_n: 376
  rep: 7
  sample_size: 10000
  scaling: 7.0
- qtl_n: 376
  rep: 8
  sample_size: 10000
  scaling: 7.0
- qtl_n: 376
  rep: 9
  sample_size: 10000
  scaling: 7.0
- qtl_n: 376
  rep: 10
  sample_size: 10000
  scaling: 7.0
- qtl_n: 490
  rep: 1
  sample_size: 10000
  scaling: 12.0
- qtl_n: 490
  rep: 2
  sample_size: 10000
  scaling: 12.0
- qtl_n: 490
  rep: 3
  sample_size: 10000
  scaling: 12.0
- qtl_n: 490
  rep: 4
  sample_size: 10000
  scaling: 12.0
- qtl_n: 490
  rep: 5
  sample_size: 10000
  scaling: 12.0
- qtl_n: 490
  rep: 6
  sample_size: 10000
  scaling: 12.0
- qtl_n: 490
  rep: 7
  sample_size: 10000
  scaling: 12.0
- qtl_n: 490
  rep: 8
  sample_size: 10000
  scaling: 12.0
- qtl_n: 490
  rep: 9
  sample_size: 10000
  scaling: 12.0
- qtl_n: 490
  rep: 10
  sample_size: 10000
  scaling: 12.0
- qtl_n: 634
  rep: 1
  sample_size: 10000
  scaling: 20.0
- qtl_n: 634
  rep: 2
  sample_size: 10000
  scaling: 20.0
- qtl_n: 634
  rep: 3
  sample_size: 10000
  scaling: 20.0
- qtl_n: 634
  rep: 4
  sample_size: 10000
  scaling: 20.0
- qtl_n: 634
  rep: 5
  sample_size: 10000
  scaling: 20.0
- qtl_n: 634
  rep: 6
  sample_size: 10000
  scaling: 20.0
- qtl_n: 634
  rep: 7
  sample_size: 10000
  scaling: 20.0
- qtl_n: 634
  rep: 8
  sample_size: 10000
  scaling: 20.0
- qtl_n: 634
  rep: 9
  sample_size: 10000
  scaling: 20.0
- qtl_n: 634
  rep: 10
  sample_size: 10000
  scaling: 20.0
- qtl_n: 142
  rep: 1
  sample_size: 100000
  scaling: 0.1
- qtl_n: 142
  rep: 2
  sample_size: 100000
  scaling: 0.1
- qtl_n: 142
  rep: 3
  sample_size: 100000
  scaling: 0.1
- qtl_n: 142
  rep: 4
  sample_size: 100000
  scaling: 0.1
- qtl_n: 142
  rep: 5
  sample_size: 100000
  scaling: 0.1
- qtl_n: 202
  rep: 1
  sample_size: 100000
  scaling: 0.2
- qtl_n: 202
  rep: 2
  sample_size: 100000
  scaling: 0.2
- qtl_n: 202
  rep: 3
  sample_size: 100000
  scaling: 0.2
- qtl_n: 202
  rep: 4
  sample_size: 100000
  scaling: 0.2
- qtl_n: 202
  rep: 5
  sample_size: 100000
  scaling: 0.2
- qtl_n: 246
  rep: 1
  sample_size: 100000
  scaling: 0.3
- qtl_n: 246
  rep: 2
  sample_size: 100000
  scaling: 0.3
- qtl_n: 246
  rep: 3
  sample_size: 100000
  scaling: 0.3
- qtl_n: 246
  rep: 4
  sample_size: 100000
  scaling: 0.3
- qtl_n: 246
  rep: 5
  sample_size: 100000
  scaling: 0.3
- qtl_n: 318
  rep: 1
  sample_size: 100000
  scaling: 0.5
- qtl_n: 318
  rep: 2
  sample_size: 100000
  scaling: 0.5
- qtl_n: 318
  rep: 3
  sample_size: 100000
  scaling: 0.5
- qtl_n: 318
  rep: 4
  sample_size: 100000
  scaling: 0.5
- qtl_n: 318
  rep: 5
  sample_size: 100000
  scaling: 0.5
- qtl_n: 448
  rep: 1
  sample_size: 100000
  scaling: 1.0
- qtl_n: 448
  rep: 2
  sample_size: 100000
  scaling: 1.0
- qtl_n: 448
  rep: 3
  sample_size: 100000
  scaling: 1.0
- qtl_n: 448
  rep: 4
  sample_size: 100000
  scaling: 1.0
- qtl_n: 448
  rep: 5
  sample_size: 100000
  scaling: 1.0
- qtl_n: 634
  rep: 1
  sample_size: 100000
  scaling: 2.0
- qtl_n: 634
  rep: 2
  sample_size: 100000
  scaling: 2.0
- qtl_n: 634
  rep: 3
  sample_size: 100000
  scaling: 2.0
- qtl_n: 634
  rep: 4
  sample_size: 100000
  scaling: 2.0
- qtl_n: 634
  rep: 5
  sample_size: 100000
  scaling: 2.0
- qtl_n: 896
  rep: 1
  sample_size: 100000
  scaling: 4.0
- qtl_n: 896
  rep: 2
  sample_size: 100000
  scaling: 4.0
- qtl_n: 896
  rep: 3
  sample_size: 100000
  scaling: 4.0
- qtl_n: 896
  rep: 4
  sample_size: 100000
  scaling: 4.0
- qtl_n: 896
  rep: 5
  sample_size: 100000
  scaling: 4.0
- qtl_n: 1184
  rep: 1
  sample_size: 100000
  scaling: 7.0
- qtl_n: 1184
  rep: 2
  sample_size: 100000
  scaling: 7.0
- qtl_n: 1184
  rep: 3
  sample_size: 100000
  scaling: 7.0
- qtl_n: 1184
  rep: 4
  sample_size: 100000
  scaling: 7.0
- qtl_n: 1184
  rep: 5
  sample_size: 100000
  scaling: 7.0
- qtl_n: 1550
  rep: 1
  sample_size: 100000
  scaling: 12.0
- qtl_n: 1550
  rep: 2
  sample_size: 100000
  scaling: 12.0
- qtl_n: 1550
  rep: 3
  sample_size: 100000
  scaling: 12.0
- qtl_n: 1550
  rep: 4
  sample_size: 100000
  scaling: 12.0
- qtl_n: 1550
  rep: 5
  sample_size: 100000
  scaling: 12.0
- qtl_n: 2002
  rep: 1
  sample_size: 100000
  scaling: 20.0
- qtl_n: 2002
  rep: 2
  sample_size: 100000
  scaling: 20.0
- qtl_n: 2002
  rep: 3
  sample_size: 100000
  scaling: 20.0
- qtl_n: 2002
  rep: 4
  sample_size: 100000
  scaling: 20.0
- qtl_n: 2002
  rep: 5
  sample_size: 100000
  scaling: 20.0
- qtl_n: 448
  rep: 1
  sample_size: 1000000
  scaling: 0.1
- qtl_n: 448
  rep: 2
  sample_size: 1000000
  scaling: 0.1
- qtl_n: 448
  rep: 3
  sample_size: 1000000
  scaling: 0.1
- qtl_n: 634
  rep: 1
  sample_size: 1000000
  scaling: 0.2
- qtl_n: 634
  rep: 2
  sample_size: 1000000
  scaling: 0.2
- qtl_n: 634
  rep: 3
  sample_size: 1000000
  scaling: 0.2
- qtl_n: 776
  rep: 1
  sample_size: 1000000
  scaling: 0.3
- qtl_n: 776
  rep: 2
  sample_size: 1000000
  scaling: 0.3
- qtl_n: 776
  rep: 3
  sample_size: 1000000
  scaling: 0.3
- qtl_n: 1002
  rep: 1
  sample_size: 1000000
  scaling: 0.5
- qtl_n: 1002
  rep: 2
  sample_size: 1000000
  scaling: 0.5
- qtl_n: 1002
  rep: 3
  sample_size: 1000000
  scaling: 0.5
- qtl_n: 1416
  rep: 1
  sample_size: 1000000
  scaling: 1.0
- qtl_n: 1416
  rep: 2
  sample_size: 1000000
  scaling: 1.0
- qtl_n: 1416
  rep: 3
  sample_size: 1000000
  scaling: 1.0
- qtl_n: 2002
  rep: 1
  sample_size: 1000000
  scaling: 2.0
- qtl_n: 2002
  rep: 2
  sample_size: 1000000
  scaling: 2.0
- qtl_n: 2002
  rep: 3
  sample_size: 1000000
  scaling: 2.0
- qtl_n: 2830
  rep: 1
  sample_size: 1000000
  scaling: 4.0
- qtl_n: 2830
  rep: 2
  sample_size: 1000000
  scaling: 4.0
- qtl_n: 2830
  rep: 3
  sample_size: 1000000
  scaling: 4.0
- qtl_n: 3742
  rep: 1
  sample_size: 1000000
  scaling: 7.0
- qtl_n: 3742
  rep: 2
  sample_size: 1000000
  scaling: 7.0
- qtl_n: 3742
  rep: 3
  sample_size: 1000000
  scaling: 7.0
- qtl_n: 4900
  rep: 1
  sample_size: 1000000
  scaling: 12.0
- qtl_n: 4900
  rep: 2
  sample_size: 1000000
  scaling: 12.0
- qtl_n: 4900
  rep: 3
  sample_size: 1000000
  scaling: 12.0
- qtl_n: 6326
  rep: 1
  sample_size: 1000000
  scaling: 20.0
- qtl_n: 6326
  rep: 2
  sample_size: 1000000
  scaling: 20.0
- qtl_n: 6326
  rep: 3
  sample_size: 1000000
  scaling: 20.0
