parameter_sets:
- qtl_n: 16
  rep: 1
  sample_size: 1000
  scaling: 0.1
- qtl_n: 16
  rep: 2
  sample_size: 1000
  scaling: 0.1
- qtl_n: 16
  rep: 3
  sample_size: 1000
  scaling: 0.1
- qtl_n: 16
  rep: 4
  sample_size: 1000
  scaling: 0.1
- qtl_n: 16
  rep: 5
  sample_size: 1000
  scaling: 0.1
- qtl_n: 22
  rep: 1
  sample_size: 1000
  scaling: 0.2
- qtl_n: 22
  rep: 2
  sample_size: 1000
  scaling: 0.2
- qtl_n: 22
  rep: 3
  sample_size: 1000
  scaling: 0.2
- qtl_n: 22
  rep: 4
  sample_size: 1000
  scaling: 0.2
- qtl_n: 22
  rep: 5
  sample_size: 1000
  scaling: 0.2
- qtl_n: 26
  rep: 1
  sample_size: 1000
  scaling: 0.3
- qtl_n: 26
  rep: 2
  sample_size: 1000
  scaling: 0.3
- qtl_n: 26
  rep: 3
  sample_size: 1000
  scaling: 0.3
- qtl_n: 26
  rep: 4
  sample_size: 1000
  scaling: 0.3
- qtl_n: 26
  rep: 5
  sample_size: 1000
  scaling: 0.3
- qtl_n: 32
  rep: 1
  sample_size: 1000
  scaling: 0.5
- qtl_n: 32
  rep: 2
  sample_size: 1000
  scaling: 0.5
- qtl_n: 32
  rep: 3
  sample_size: 1000
  scaling: 0.5
- qtl_n: 32
  rep: 4
  sample_size: 1000
  scaling: 0.5
- qtl_n: 32
  rep: 5
  sample_size: 1000
  scaling: 0.5
- qtl_n: 46
  rep: 1
  sample_size: 1000
  scaling: 1.0
- qtl_n: 46
  rep: 2
  sample_size: 1000
  scaling: 1.0
- qtl_n: 46
  rep: 3
  sample_size: 1000
  scaling: 1.0
- qtl_n: 46
  rep: 4
  sample_size: 1000
  scaling: 1.0
- qtl_n: 46
  rep: 5
  sample_size: 1000
  scaling: 1.0
- qtl_n: 64
  rep: 1
  sample_size: 1000
  scaling: 2.0
- qtl_n: 64
  rep: 2
  sample_size: 1000
  scaling: 2.0
- qtl_n: 64
  rep: 3
  sample_size: 1000
  scaling: 2.0
- qtl_n: 64
  rep: 4
  sample_size: 1000
  scaling: 2.0
- qtl_n: 64
  rep: 5
  sample_size: 1000
  scaling: 2.0
- qtl_n: 90
  rep: 1
  sample_size: 1000
  scaling: 4.0
- qtl_n: 90
  rep: 2
  sample_size: 1000
  scaling: 4.0
- qtl_n: 90
  rep: 3
  sample_size: 1000
  scaling: 4.0
- qtl_n: 90
  rep: 4
  sample_size: 1000
  scaling: 4.0
- qtl_n: 90
  rep: 5
  sample_size: 1000
  scaling: 4.0
- qtl_n: 120
  rep: 1
  sample_size: 1000
  scaling: 7.0
- qtl_n: 120
  rep: 2
  sample_size: 1000
  scaling: 7.0
- qtl_n: 120
  rep: 3
  sample_size: 1000
  scaling: 7.0
- qtl_n: 120
  rep: 4
  sample_size: 1000
  scaling: 7.0
- qtl_n: 120
  rep: 5
  sample_size: 1000
  scaling: 7.0
- qtl_n: 156
  rep: 1
  sample_size: 1000
  scaling: 12.0
- qtl_n: 156
  rep: 2
  sample_size: 1000
  scaling: 12.0
- qtl_n: 156
  rep: 3
  sample_size: 1000
  scaling: 12.0
- qtl_n: 156
  rep: 4
  sample_size: 1000
  scaling: 12.0
- qtl_n: 156
  rep: 5
  sample_size: 1000
  scaling: 12.0
- qtl_n: 202
  rep: 1
  sample_size: 1000
  scaling: 20.0
- qtl_n: 202
  rep: 2
  sample_size: 1000
  scaling: 20.0
- qtl_n: 202
  rep: 3
  sample_size: 1000
  scaling: 20.0
- qtl_n: 202
  rep: 4
  sample_size: 1000
  scaling: 20.0
- qtl_n: 202
  rep: 5
  sample_size: 1000
  scaling: 20.0
- qtl_n: 46
  rep: 1
  sample_size: 10000
  scaling: 0.1
- qtl_n: 46
  rep: 2
  sample_size: 10000
  scaling: 0.1
- qtl_n: 46
  rep: 3
  sample_size: 10000
  scaling: 0.1
- qtl_n: 46
  rep: 4
  sample_size: 10000
  scaling: 0.1
- qtl_n: 46
  rep: 5
  sample_size: 10000
  scaling: 0.1
- qtl_n: 64
  rep: 1
  sample_size: 10000
  scaling: 0.2
- qtl_n: 64
  rep: 2
  sample_size: 10000
  scaling: 0.2
- qtl_n: 64
  rep: 3
  sample_size: 10000
  scaling: 0.2
- qtl_n: 64
  rep: 4
  sample_size: 10000
  scaling: 0.2
- qtl_n: 64
  rep: 5
  sample_size: 10000
  scaling: 0.2
- qtl_n: 78
  rep: 1
  sample_size: 10000
  scaling: 0.3
- qtl_n: 78
  rep: 2
  sample_size: 10000
  scaling: 0.3
- qtl_n: 78
  rep: 3
  sample_size: 10000
  scaling: 0.3
- qtl_n: 78
  rep: 4
  sample_size: 10000
  scaling: 0.3
- qtl_n: 78
  rep: 5
  sample_size: 10000
  scaling: 0.3
- qtl_n: 102
  rep: 1
  sample_size: 10000
  scaling: 0.5
- qtl_n: 102
  rep: 2
  sample_size: 10000
  scaling: 0.5
- qtl_n: 102
  rep: 3
  sample_size: 10000
  scaling: 0.5
- qtl_n: 102
  rep: 4
  sample_size: 10000
  scaling: 0.5
- qtl_n: 102
  rep: 5
  sample_size: 10000
  scaling: 0.5
- qtl_n: 142
  rep: 1
  sample_size: 10000
  scaling: 1.0
- qtl_n: 142
  rep: 2
  sample_size: 10000
  scaling: 1.0
- qtl_n: 142
  rep: 3
  sample_size: 10000
  scaling: 1.0
- qtl_n: 142
  rep: 4
  sample_size: 10000
  scaling: 1.0
- qtl_n: 142
  rep: 5
  sample_size: 10000
  scaling: 1.0
- qtl_n: 202
  rep: 1
  sample_size: 10000
  scaling: 2.0
- qtl_n: 202
  rep: 2
  sample_size: 10000
  scaling: 2.0
- qtl_n: 202
  rep: 3
  sample_size: 10000
  scaling: 2.0
- qtl_n: 202
  rep: 4
  sample_size: 10000
  scaling: 2.0
- qtl_n: 202
  rep: 5
  sample_size: 10000
  scaling: 2.0
- qtl_n: 284
  rep: 1
  sample_size: 10000
  scaling: 4.0
- qtl_n: 284
  rep: 2
  sample_size: 10000
  scaling: 4.0
- qtl_n: 284
  rep: 3
  sample_size: 10000
  scaling: 4.0
- qtl_n: 284
  rep: 4
  sample_size: 10000
  scaling: 4.0
- qtl_n: 284
  rep: 5
  sample_size: 10000
  scaling: 4.0
- qtl_n: 376
  rep: 1
  sample_size: 10000
  scaling: 7.0
- qtl_n: 376
  rep: 2
  sample_size: 10000
  scaling: 7.0
- qtl_n: 376
  rep: 3
  sample_size: 10000
  scaling: 7.0
- qtl_n: 376
  rep: 4
  sample_size: 10000
  scaling: 7.0
- qtl_n: 376
  rep: 5
  sample_size: 10000
  scaling: 7.0
- qtl_n: 490
  rep: 1
  sample_size: 10000
  scaling: 12.0
- qtl_n: 490
  rep: 2
  sample_size: 10000
  scaling: 12.0
- qtl_n: 490
  rep: 3
  sample_size: 10000
  scaling: 12.0
- qtl_n: 490
  rep: 4
  sample_size: 10000
  scaling: 12.0
- qtl_n: 490
  rep: 5
  sample_size: 10000
  scaling: 12.0
- qtl_n: 634
  rep: 1
  sample_size: 10000
  scaling: 20.0
- qtl_n: 634
  rep: 2
  sample_size: 10000
  scaling: 20.0
- qtl_n: 634
  rep: 3
  sample_size: 10000
  scaling: 20.0
- qtl_n: 634
  rep: 4
  sample_size: 10000
  scaling: 20.0
- qtl_n: 634
  rep: 5
  sample_size: 10000
  scaling: 20.0
