parameter_sets:
- qtl_n: 16
  sample_size: 1000
  scaling: 0.1
- qtl_n: 22
  sample_size: 1000
  scaling: 0.2
- qtl_n: 26
  sample_size: 1000
  scaling: 0.3
- qtl_n: 32
  sample_size: 1000
  scaling: 0.5
- qtl_n: 46
  sample_size: 1000
  scaling: 1.0
- qtl_n: 64
  sample_size: 1000
  scaling: 2.0
- qtl_n: 90
  sample_size: 1000
  scaling: 4.0
- qtl_n: 120
  sample_size: 1000
  scaling: 7.0
- qtl_n: 156
  sample_size: 1000
  scaling: 12.0
- qtl_n: 202
  sample_size: 1000
  scaling: 20.0
- qtl_n: 46
  sample_size: 10000
  scaling: 0.1
- qtl_n: 64
  sample_size: 10000
  scaling: 0.2
- qtl_n: 78
  sample_size: 10000
  scaling: 0.3
- qtl_n: 102
  sample_size: 10000
  scaling: 0.5
- qtl_n: 142
  sample_size: 10000
  scaling: 1.0
- qtl_n: 202
  sample_size: 10000
  scaling: 2.0
- qtl_n: 284
  sample_size: 10000
  scaling: 4.0
- qtl_n: 376
  sample_size: 10000
  scaling: 7.0
- qtl_n: 490
  sample_size: 10000
  scaling: 12.0
- qtl_n: 634
  sample_size: 10000
  scaling: 20.0
- qtl_n: 142
  sample_size: 100000
  scaling: 0.1
- qtl_n: 202
  sample_size: 100000
  scaling: 0.2
- qtl_n: 246
  sample_size: 100000
  scaling: 0.3
- qtl_n: 318
  sample_size: 100000
  scaling: 0.5
- qtl_n: 448
  sample_size: 100000
  scaling: 1.0
- qtl_n: 634
  sample_size: 100000
  scaling: 2.0
- qtl_n: 896
  sample_size: 100000
  scaling: 4.0
- qtl_n: 1184
  sample_size: 100000
  scaling: 7.0
- qtl_n: 1550
  sample_size: 100000
  scaling: 12.0
- qtl_n: 2002
  sample_size: 100000
  scaling: 20.0
- qtl_n: 448
  sample_size: 1000000
  scaling: 0.1
- qtl_n: 634
  sample_size: 1000000
  scaling: 0.2
- qtl_n: 776
  sample_size: 1000000
  scaling: 0.3
- qtl_n: 1002
  sample_size: 1000000
  scaling: 0.5
- qtl_n: 1416
  sample_size: 1000000
  scaling: 1.0
- qtl_n: 2002
  sample_size: 1000000
  scaling: 2.0
- qtl_n: 2830
  sample_size: 1000000
  scaling: 4.0
- qtl_n: 3742
  sample_size: 1000000
  scaling: 7.0
- qtl_n: 4900
  sample_size: 1000000
  scaling: 12.0
- qtl_n: 6326
  sample_size: 1000000
  scaling: 20.0
